### ISSUE TITLE
Heka is deprecated

### ISSUE THREAD

**Issue by philandstuff** [MonsantoCo/cf-metrics#11]
Heka is deprecated.  See [its github page](https://github.com/mozilla-services/heka) and [the explanatory email](https://mail.mozilla.org/pipermail/heka/2016-May/001059.html).  You may wish to consider migrating to another tool.

**Comment by mjseid** [comment]
Yes, unfortunately Heka as abandoned.

At first I was waiting for hindsight to have an easy migration path from heka, so we could use that.  But hindsight hasn't gotten much traction and definitely doesn't have an easy path.

Since then the TICK stack (influx, kapacitor specifically) have really taken off.  So current thought is to refactor this stack to use that once I get time (hopefully in the next few months).  Heka does still work and we've been using this stack in production for the past 2 years so it hasn't been top of the priority list.

Current thought is we'd use the influxdb firehose nozzle to send metrics straight to influx, and then use kapacitor to do the alerting part.  I've only lightly touched kapacitor to date, but it seems like it should handle the scale and speed needed for doing the alert queries and sending notifications to slack.

**Comment by mjseid** [comment]
Phil, 
    we've dedicated some time to this and I believe we're at MVP with functionality with the new stack that replaces heka.  We still need to polish some things up, and redo the documentation but would you be interested in helping test this in a beta branch?

If so please let me know and I'll create one for the current state with some bare-bones documentation.  I'd love to hear your feedback (or possibly PR's :-) ) especially if you've been using the project as is.

**Comment by nikolayantonov** [comment]
Hi mjseid, 
We are interested in testing your project and feedback sharing. Looking forward to a new branch :)

**Comment by philandstuff** [comment]
I'm not interested in trying a beta, but thank you very much for the offer!

**Comment by mjseid** [comment]
Np @philandstuff , thanks for nudging us to get this moving.

@nikolayantonov , sounds great.  I've created a _tick_ branch with the in-progress code.  Please try it out and let us know what you think.  

I'm closing this ticket, but please open others related to the new code as you encounter things
